apiVersion: v1
kind: Namespace
metadata:
  name: studynotes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: studynotes
  namespace: studynotes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: studynotes
  template:
    metadata:
      labels:
        app: studynotes
    spec:
      automountServiceAccountToken: false

      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: app
          image: studynotes:p12-local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000

          env:
            - name: DATABASE_URL
              value: "sqlite:////data/app.db"

          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]

          volumeMounts:
            - name: data
              mountPath: /data
            - name: tmp
              mountPath: /tmp

      volumes:
        - name: data
          emptyDir: {}
        - name: tmp
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: studynotes
  namespace: studynotes
spec:
  selector:
    app: studynotes
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: studynotes-default
  namespace: studynotes
spec:
  podSelector:
    matchLabels:
      app: studynotes
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 8000
  egress:
    - {}